/**
 * The ownership/handover document: its data, its rendering, the provenance tags on every row, and the
 * promise that no raw secret reaches either artifact. Providers are fakes; nothing here touches a
 * network or a real account.
 */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { _resetSecretRegistry, Secret } from '../src/core/secret.js';
import { emptyState } from '../src/core/state.js';
import { buildHandover, type HandoverDoc, type HandoverInput } from '../src/handover/build.js';
import { assertOverwritable, handoverJson, handoverPaths, renderHandover } from '../src/report/handover.js';
import type { Adapter, ProjectRef, ShipConfig, ShipState } from '../src/core/types.js';
import { detectFixture, testCtx } from './helpers.js';
import { ALL_RAW_SECRETS, RAW, fakeWorld, type FakeWorld } from './fakes.js';

beforeEach(() => _resetSecretRegistry());

const CONFIG: Partial<ShipConfig> = {
  stack: { hosting: 'fakehost', db: 'fakedb', auth: 'fakedb', payments: 'fakepay', email: 'fakemail', dns: 'fakedns' },
  domain: 'example.com',
  email: { from: 'Shop <hello@example.com>', domain: 'send.example.com' },
};

const CHECKS = ['accounts', 'env-parity', 'domain-live', 'webhook-registered', 'webhook-unsigned', 'stripe-live-ready', 'email-dns', 'email-verified', 'auth-redirects', 'db-connection', 'rls-probe', 'bundle-secrets', 'netlify-public-access'];

const HANDOFFS: HandoverInput['handoffs'] = [
  { id: 'login:fakehost', why: 'the FakeHost CLI is not logged in', action: 'Run `fakehost login` in your own terminal window', blocking: true, done: false, evidence: ['not logged in'] },
  { id: 'fakepay:activate', why: 'the payment account needs identity verification', action: 'Finish the payment account activation', url: 'https://example.test/onboarding', blocking: true, manual: true, done: null, evidence: [] },
  { id: 'already-done', why: 'nothing left', action: 'Nothing to do here', blocking: false, manual: true, done: true, evidence: [] },
];

const STATE: ShipState = {
  ...emptyState(),
  resources: {
    'fakehost.projectId': 'prj_1',
    'fakehost.projectName': 'shop',
    'fakehost.createdProjectId': 'prj_1',
    'fakepay.test.webhookEndpointId': 'we_test',
    'fakemail.keyId@production': 'key_9',
    'supabase.ref': 'abcdefghijklmnop',
    'supabase.createdByGolive': 'abcdefghijklmnop',
    'resend.domainId': 'dom_42',
  },
  steps: {
    'payments:webhook:production': { status: 'done', at: '2026-08-01T10:00:00.000Z', planId: 'plan-1' },
    'email:key:production': { status: 'done', at: '2026-08-02T10:00:00.000Z', planId: 'plan-1' },
    'email:domain': { status: 'done', at: '2026-08-03T10:00:00.000Z', planId: 'plan-1' },
  },
};

const HOST_PROJECT: ProjectRef = { id: 'prj_1', name: 'shop', scope: { kind: 'team', id: 'team_1', name: 'acme' } };

function arrange(w: FakeWorld): void {
  w.host.current = { ...HOST_PROJECT };
  w.db.current = { id: 'db_1', name: 'shop', scope: { kind: 'organization', id: 'org_1', name: 'Acme Org' } };
  w.dns.owned = [
    { type: 'TXT', name: '_vercel.example.com', content: 'vc-domain-verify=shop,abc123' },
    { type: 'CNAME', name: 'www.example.com', content: 'shop.fakehost.app' },
  ];
  w.pay.endpoints = [{ id: 'we_test', url: 'https://example.com/api/webhooks/stripe', events: ['checkout.session.completed'], enabled: true, mode: 'test' }];
}

function setup(opts: { state?: ShipState; adapters?: Adapter[]; handoffs?: HandoverInput['handoffs']; checkIds?: readonly string[]; config?: Partial<ShipConfig> } = {}) {
  const w = fakeWorld();
  arrange(w);
  const ctx = testCtx({ cwd: '/work/shop', adapters: opts.adapters ?? w.adapters, config: { ...CONFIG, ...opts.config }, state: opts.state ?? STATE, detect: { framework: 'next' } });
  return {
    w,
    ctx,
    build: () => buildHandover(ctx, { handoffs: opts.handoffs ?? HANDOFFS, checkIds: opts.checkIds ?? CHECKS }),
  };
}

describe('handover: data', () => {
  it('names the product, the release and the URLs the host reported in this run', async () => {
    const doc = await setup().build();
    expect(doc.generator).toBe('Generated by golive');
    expect(doc.version).toBe(1);
    expect(doc.generatedAt).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(doc.product).toEqual({ name: 'shop', root: '/work/shop', framework: 'next', domain: 'example.com' });
    expect(doc.release.version).toBeTruthy();
    expect(doc.release.bundleDigest).toBeTruthy();
    expect(doc.urls).toEqual({ preview: 'https://shop-git-main.fakehost.app', production: 'https://shop.fakehost.app' });
    expect(doc.limits.join(' ')).toMatch(/\[verified by golive\]/);
  });

  it('reports each account with its provider, auth route, team/org name and login instruction', async () => {
    const doc = await setup().build();
    const hosting = doc.accounts.find((a) => a.axis === 'hosting')!;
    expect(hosting).toMatchObject({ provider: 'fakehost', providerTitle: 'FakeHost', via: 'fakehost CLI', account: 'acme', provenance: { kind: 'verified' } });
    expect(hosting.login).toMatch(/connected/);
    expect(doc.accounts.find((a) => a.axis === 'db')).toMatchObject({ provider: 'fakedb', account: 'Acme Org' });
    expect(doc.accounts.find((a) => a.axis === 'payments')).toMatchObject({ provider: 'fakepay', provenance: { kind: 'verified' } });
  });

  it('marks a provider golive cannot log in to as unverifiable, and a failed check as unknown', async () => {
    const guided = fakeWorld().adapters.map((a) => (a.id === 'fakepay' ? { ...a, automated: false } : a));
    const doc = await setup({ adapters: guided }).build();
    expect(doc.accounts.find((a) => a.axis === 'payments')).toMatchObject({ provenance: { kind: 'unverifiable' } });

    const broken = fakeWorld().adapters.map((a) => (a.id === 'fakemail' ? { ...a, auth: async () => { throw new Error('fakemail CLI is missing'); } } : a));
    const other = await setup({ adapters: broken }).build();
    expect(other.accounts.find((a) => a.axis === 'email')).toMatchObject({ provenance: { kind: 'unknown' } });
    expect(other.accounts.find((a) => a.axis === 'email')!.login).toMatch(/could not check/);
  });

  it('lists every resource with its id, ownership proof and how it was checked', async () => {
    const doc = await setup().build();
    const byName = (n: string) => doc.resources.filter((r) => r.kind === n);

    const dns = byName('DNS record');
    expect(dns.map((r) => [r.name, r.id])).toEqual([['CNAME www.example.com', 'shop.fakehost.app'], ['TXT _vercel.example.com', 'vc-domain-verify=shop,abc123']]);
    expect(dns[0]).toMatchObject({ axis: 'dns', provider: 'fakedns', ownership: 'created', removable: true, provenance: { kind: 'verified' } });
    expect(dns[0]!.proof).toMatch(/lists it as golive-owned/);

    expect(byName('webhook endpoint')).toEqual([
      expect.objectContaining({ axis: 'payments', id: 'we_test', ownership: 'created', removable: true, provenance: { kind: 'recorded', at: '2026-08-01T10:00:00.000Z' } }),
    ]);
    expect(byName('sending key')).toEqual([
      expect.objectContaining({ axis: 'email', id: 'key_9', provenance: { kind: 'recorded', at: '2026-08-02T10:00:00.000Z' } }),
    ]);
    const project = byName('host project')[0]!;
    expect(project).toMatchObject({ provider: 'fakehost', name: 'shop', id: 'prj_1', url: 'https://shop.fakehost.app', ownership: 'created', provenance: { kind: 'verified' } });
    expect(project.proof).toMatch(/creation marker \(fakehost\.createdProjectId\)/);

    const db = byName('database project')[0]!;
    expect(db).toMatchObject({ axis: 'db', provider: 'supabase', id: 'abcdefghijklmnop', ownership: 'created' });
    expect(db.proof).toMatch(/supabase\.ref/);
    expect(byName('sending domain')[0]).toMatchObject({ axis: 'email', provider: 'resend', name: 'send.example.com', id: 'dom_42', provenance: { kind: 'recorded', at: '2026-08-03T10:00:00.000Z' } });
  });

  it('never claims a resource golive adopted, and keeps it out of the removable set', async () => {
    const doc = await setup({ state: { ...STATE, resources: { ...STATE.resources, 'fakehost.createdProjectId': 'prj_other' } } }).build();
    const project = doc.resources.find((r) => r.kind === 'host project')!;
    expect(project).toMatchObject({ ownership: 'adopted', removable: false });
    expect(project.proof).toMatch(/no creation marker/);
    expect(doc.retirement.find((r) => r.resource.includes('(prj_1)'))).toMatchObject({ removable: false, how: expect.stringMatching(/adopted this project/) });
  });

  it('states no cost figure and points at the provider billing pages instead', async () => {
    const doc = await setup().build();
    expect(doc.costs.map((c) => c.providerTitle)).toEqual(['FakeHost', 'FakeDB', 'FakePay', 'FakeMail', 'FakeDNS']);
    for (const c of doc.costs) {
      expect(c.read).toMatch(/nothing/);
      expect(c.provenance).toEqual({ kind: 'unknown' });
      expect(c.where).toMatch(/billing|Billing/);
    }
    expect(JSON.stringify(doc)).not.toMatch(/[$€£]\s?\d|\d+\s?(USD|EUR|GBP)\b/);
  });

  it('lists the open handoffs, the closed count and the jobs that come back', async () => {
    const doc = await setup().build();
    expect(doc.manualClosed).toBe(1);
    const handoffs = doc.manual.filter((m) => m.kind === 'handoff');
    expect(handoffs.map((h) => [h.title, h.blocking, h.provenance])).toEqual([
      ['login:fakehost', true, { kind: 'verified' }],
      ['fakepay:activate', true, { kind: 'unverifiable' }],
    ]);
    const recurring = doc.manual.filter((m) => m.kind === 'recurring').map((m) => m.title);
    expect(recurring.join(' ')).toMatch(/DMARC/);
    expect(recurring.join(' ')).toMatch(/rotate/);
    expect(recurring.join(' ')).toMatch(/back up/);
    expect(recurring.join(' ')).toMatch(/renew example\.com/);
    for (const m of doc.manual.filter((x) => x.kind === 'recurring')) expect(m.provenance).toEqual({ kind: 'unverifiable' });
  });

  it('gives per-subject commands that only name registered checks, and where the evidence lives', async () => {
    const doc = await setup().build();
    expect(doc.runbook.find((r) => r.subject === 'hosting (FakeHost)')!.commands).toEqual(['golive doctor', 'golive verify --only domain-live,env-parity,netlify-public-access,bundle-secrets']);
    expect(doc.runbook.find((r) => r.subject === 'payments (FakePay)')!.commands[1]).toBe('golive verify --only webhook-registered,webhook-unsigned,stripe-live-ready');
    expect(doc.runbook.find((r) => r.subject === 'whole app')!.commands.join(' ')).toMatch(/plan.*apply --plan <planId> --yes.*verify/);
    expect(doc.evidence.join(' ')).toMatch(/\.golive\/state\.json/);
    expect(doc.evidence.join(' ')).toMatch(/GOLIVE_REPORT\.md/);

    // A check this release does not register is never offered as a command.
    const partial = await setup({ checkIds: ['accounts'] }).build();
    expect(partial.runbook.find((r) => r.subject === 'hosting (FakeHost)')!.commands).toEqual(['golive doctor']);
    expect(partial.runbook.find((r) => r.subject === 'hosting (FakeHost)')!.note).toMatch(/no registered check/);
  });

  it('names the removal gates and what has to be done by hand', async () => {
    const doc = await setup().build();
    const dns = doc.retirement.find((r) => r.resource.includes('CNAME www.example.com'))!;
    expect(dns.how).toMatch(/--confirm-destroy --confirm-dns/);
    expect(doc.retirement.find((r) => r.resource.includes('webhook endpoint we_test'))!.how).toMatch(/--confirm-destroy/);
    expect(doc.retirement.find((r) => r.resource.includes('Supabase project'))!.how).toMatch(/by hand in the dashboard/);
    expect(doc.retirement.find((r) => r.resource.includes('project shop'))!.how).toMatch(/--confirm-destroy/);
    expect(doc.retirement.find((r) => r.resource.includes('CNAME'))!.removable).toBe(true);
    expect(doc.retirement.find((r) => r.resource.includes('Supabase project'))!.removable).toBe(false);
  });

  it('records a resource golive cannot remove right now instead of dropping it', async () => {
    const signedOut = fakeWorld().adapters.map((a) => (a.id === 'fakepay' ? { ...a, auth: async () => ({ ok: false, howToFix: 'run `fakepay login`' }) } : a));
    const doc = await setup({ adapters: signedOut }).build();
    const webhook = doc.resources.find((r) => r.kind === 'webhook endpoint')!;
    expect(webhook).toMatchObject({ id: 'we_test', removable: false });
    expect(doc.retirement.find((r) => r.resource.includes(webhook.id))).toMatchObject({ removable: false });
    expect(doc.retirement.find((r) => r.resource.includes(webhook.id))!.how).toMatch(/golive cannot remove it right now/);
  });

  it('labels every row with the provenance vocabulary and points each section at its source', async () => {
    const markdown = renderHandover(await setup().build());
    expect(markdown).toContain('[verified by golive]');
    expect(markdown).toContain('[recorded 2026-08-01, not re-checked]');
    expect(markdown).toContain('[not verifiable by golive]');
    expect(markdown).toContain('[unknown]');
    const doc = await setup().build();
    expect(doc.provenance.map((p) => p.section)).toEqual(['Accounts and login route', 'Resources created', 'Costs and recurrence', 'What is manual', 'If it breaks', 'Retirement']);
    for (const p of doc.provenance) expect(p.at).toMatch(/^\d{4}-\d{2}-\d{2}T/);
  });
});

// ── Rendering ───────────────────────────────────────────────────────────────────────────────────

describe('handover: rendering', () => {
  it('renders every section, in order, with the tag on each row', async () => {
    const doc = await setup().build();
    const markdown = renderHandover(doc);
    const headings = markdown.split('\n').filter((l) => l.startsWith('## '));
    expect(headings).toEqual([
      '## Accounts and login route',
      '## Resources created',
      '## Costs and recurrence',
      '## What is manual',
      '## If it breaks',
      '## Retirement',
      '## Provenance',
    ]);
    expect(markdown).toMatch(/^# Ownership and handover$/m);
    expect(markdown).toMatch(/^_Generated \d{4}-\d{2}-\d{2}T/m);
    expect(markdown).toContain('bundle');
    expect(markdown).toContain('| hosting | FakeHost | fakehost CLI [verified by golive] | acme |');
    expect(markdown).toContain('| dns | FakeDNS | CNAME www.example.com | shop.fakehost.app | — | created by golive |');
    expect(markdown).toMatch(/\[recorded 2026-08-01, not re-checked\]/);
    expect(markdown).toMatch(/\*\*\[blocking\]\*\* Run `fakehost login` in your own terminal window/);
    expect(markdown).toContain('Handoff id: `login:fakehost`');
    expect(markdown).toContain('`golive verify --only domain-live,env-parity,netlify-public-access,bundle-secrets`');
    expect(markdown).toMatch(/renew example\.com/);
    expect(markdown.trimEnd().endsWith('review it before sharing it.')).toBe(true);
  });

  it('renders an empty but honest document when golive created nothing', async () => {
    const doc = await setup({
      state: emptyState(),
      config: { stack: {}, domain: undefined, email: undefined },
      handoffs: [],
      checkIds: [],
    }).build();
    const markdown = renderHandover(doc);
    expect(doc.resources).toEqual([]);
    expect(markdown).toContain('_golive found no resource it created or adopted._');
    expect(markdown).toContain('_No providers are configured yet._');
    expect(markdown).toContain('_Nothing is outstanding._');
    expect(markdown).toContain('_Nothing golive created was found to remove._');
    expect(markdown).toContain('**Live URLs:** none');
  });

  it('escapes a pipe inside a table cell so the table stays intact', async () => {
    const doc = await setup({ state: { ...STATE, resources: { ...STATE.resources, 'fakehost.projectName': 'shop|prod' } } }).build();
    const markdown = renderHandover(doc);
    expect(markdown).toContain('| shop\\|prod |');
  });
});

// ── Secrets ─────────────────────────────────────────────────────────────────────────────────────

describe('handover: secret freedom', () => {
  it('contains no raw secret from any provider, even when a provider read hands one back', async () => {
    // Register the raw values exactly as a live run would, then have a provider read return one.
    const secrets = [new Secret('FAKEDB_ACCESS_TOKEN', RAW.supabaseSecret), new Secret('RESEND_API_KEY', RAW.resendKey), new Secret('STRIPE_SECRET_KEY', RAW.stripeLive)];
    const leaky = fakeWorld().adapters.map((a) =>
      a.id === 'fakemail' ? { ...a, auth: async () => ({ ok: true, via: `fakemail CLI (key ${RAW.resendKey})` }) } : a,
    );
    const handoffs: HandoverInput['handoffs'] = [{ id: 'x', why: `the key ${RAW.supabaseSecret} was rejected`, action: `rotate ${RAW.stripeLive}`, blocking: true, done: false, evidence: [] }];
    const ctx = testCtx({
      cwd: '/work/shop',
      adapters: leaky,
      config: { ...CONFIG, projects: { hosting: 'shop', db: 'abcd1234' } },
      state: { ...STATE, secrets: { 'RESEND_API_KEY@production': { fp: secrets[1]!.fingerprint, at: '2026-08-02T10:00:00.000Z' } } },
    });
    const doc = await buildHandover(ctx, { handoffs, checkIds: CHECKS });
    const markdown = renderHandover(doc);
    const json = handoverJson(doc);

    for (const raw of ALL_RAW_SECRETS()) {
      expect(markdown, raw).not.toContain(raw);
      expect(json, raw).not.toContain(raw);
    }
    // The document still says what it could: a redacted route, not a missing row.
    expect(markdown).toContain('[redacted');
    expect(JSON.parse(json)).toMatchObject({ generator: 'Generated by golive', version: 1 });
  });

  it('never reads state.secrets or an Outputs value into the document', async () => {
    const ctx = testCtx({ cwd: '/work/shop', adapters: fakeWorld().adapters, config: CONFIG, state: STATE });
    const doc = await buildHandover(ctx, { handoffs: [], checkIds: [] });
    const text = JSON.stringify(doc);
    expect(text).not.toContain('secrets');
    expect(text).not.toMatch(/"(secret|value|key)"\s*:\s*"[^"]{8,}"/);
    // Only names, ids, URLs and fingerprints are ever written down.
    expect(doc.resources.every((r) => r.id.length > 0 && !r.id.includes('postgres'))).toBe(true);
  });
});

// ── Overwrite guard ─────────────────────────────────────────────────────────────────────────────

describe('handover: overwrite guard', () => {
  let root: string;
  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'golive-handover-'));
  });
  afterEach(() => rmSync(root, { recursive: true, force: true }));

  it('accepts a missing file, its own file, and refuses any other one', () => {
    const { markdown } = handoverPaths(root);
    expect(() => assertOverwritable(markdown, false)).not.toThrow();
    writeFileSync(markdown, '# Ownership and handover\n\nGenerated by golive. This file contains no secrets.\n');
    expect(() => assertOverwritable(markdown, false)).not.toThrow();

    writeFileSync(markdown, 'my own private notes\n');
    expect(() => assertOverwritable(markdown, false)).toThrow(/carries no "Generated by golive" marker/);
    expect(() => assertOverwritable(markdown, true)).not.toThrow();
    expect(readFileSync(markdown, 'utf8')).toBe('my own private notes\n'); // the guard never rewrites
  });

  it('refuses a symlink or a directory instead of following it', () => {
    const { json } = handoverPaths(root);
    mkdirSync(json, { recursive: true });
    expect(() => assertOverwritable(json, false)).toThrow(/not a regular file/);
  });
});

// ── CLI surface ─────────────────────────────────────────────────────────────────────────────────

const mocks = vi.hoisted(() => ({ detect: vi.fn(), plan: vi.fn(), exec: vi.fn() }));
vi.mock('../src/core/exec.js', () => ({ exec: mocks.exec }));
vi.mock('../src/core/credentials.js', async (original) => ({
  ...await original<typeof import('../src/core/credentials.js')>(),
  credentialsStatus: () => ({ exists: false, private: null }),
}));
vi.mock('../src/detect/index.js', () => ({ detect: mocks.detect }));
vi.mock('../src/core/plan.js', async (original) => ({ ...await original<typeof import('../src/core/plan.js')>(), buildPlan: mocks.plan }));
vi.mock('../src/registry.js', async (original) => ({
  ...await original<typeof import('../src/registry.js')>(),
  ADAPTERS: [], CHECKS: [], adapterFor: () => undefined, linkList: () => [], checkMap: () => new Map(),
}));

const oldArgv = process.argv;

async function runCli(root: string, args: string[]) {
  vi.resetModules();
  process.argv = ['node', 'golive', ...args, '--cwd', root, '--json'];
  const chunks: string[] = [];
  const stdout = vi.spyOn(process.stdout, 'write').mockImplementation((chunk) => { chunks.push(String(chunk)); return true; });
  const exit = vi.spyOn(process, 'exit').mockImplementation(() => undefined as never);
  await import('../src/cli.js');
  await vi.waitFor(() => expect(exit).toHaveBeenCalled());
  const result = { output: chunks.join(''), code: exit.mock.calls.at(-1)?.[0] as number | undefined };
  stdout.mockRestore(); exit.mockRestore();
  return result;
}

describe('handoff --write', () => {
  let root: string;
  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), 'golive-handover-cli-'));
    writeFileSync(join(root, 'golive.yaml'), JSON.stringify({ version: 1, stack: {}, targets: ['production'] }));
    vi.clearAllMocks();
    mocks.detect.mockResolvedValue(detectFixture());
    mocks.plan.mockResolvedValue({ handoffs: [
      { id: 'login:fakehost', why: 'not logged in', action: 'Log in', blocking: true },
      { id: 'fakepay:activate', why: 'identity check', action: 'Finish activation', blocking: true, manual: true },
    ], steps: [] });
    mocks.exec.mockImplementation(() => { throw new Error('handover tests must not run provider CLIs'); });
    vi.stubGlobal('fetch', vi.fn(() => { throw new Error('handover tests must not use the network'); }));
  });
  afterEach(() => {
    process.argv = oldArgv;
    vi.restoreAllMocks();
    vi.unstubAllGlobals();
    rmSync(root, { recursive: true, force: true });
  });

  it('leaves the default handoff output and the filesystem untouched', async () => {
    const result = await runCli(root, ['handoff']);
    expect(result.code).toBe(0);
    expect(JSON.parse(result.output)).toEqual({
      ok: false,
      handoffs: [
        expect.objectContaining({ id: 'login:fakehost', done: false }),
        expect.objectContaining({ id: 'fakepay:activate', done: null }),
      ],
      unverified: ['fakepay:activate'],
      note: 'items with done:null cannot be verified by golive — confirm them with the human and name them as unverified in your summary',
    });
    expect(existsSync(join(root, 'GOLIVE_HANDOVER.md'))).toBe(false);
    expect(existsSync(join(root, '.golive/handover.json'))).toBe(false);
  });

  it('writes both artifacts and reports their paths, mirroring reportPaths', async () => {
    const result = await runCli(root, ['handoff', '--write']);
    const output = JSON.parse(result.output);
    expect(result.code).toBe(0);
    expect(output.handoverPaths).toEqual(handoverPaths(root));
    const markdown = readFileSync(join(root, 'GOLIVE_HANDOVER.md'), 'utf8');
    expect(markdown).toContain('Generated by golive');
    expect(markdown).toContain('# Ownership and handover');
    expect(markdown).toContain('## Retirement');
    const json = JSON.parse(readFileSync(join(root, '.golive/handover.json'), 'utf8')) as HandoverDoc;
    expect(json).toMatchObject({ generator: 'Generated by golive', version: 1 });
    expect(output.handover).toMatchObject({ generatedAt: json.generatedAt, resources: json.resources.length });

    // Its own artifacts are replaced on the next run without --force.
    const again = await runCli(root, ['handoff', '--write']);
    expect(again.code).toBe(0);
    expect(JSON.parse(again.output).handoverPaths).toEqual(handoverPaths(root));
  });

  it('refuses to overwrite a file golive did not write, in either artifact, and writes neither', async () => {
    writeFileSync(join(root, 'GOLIVE_HANDOVER.md'), 'my own private notes\n');
    const refused = await runCli(root, ['handoff', '--write']);
    expect(refused.code).toBe(1);
    expect(JSON.parse(refused.output).error.message).toMatch(/GOLIVE_HANDOVER\.md exists and carries no "Generated by golive" marker/);
    expect(readFileSync(join(root, 'GOLIVE_HANDOVER.md'), 'utf8')).toBe('my own private notes\n');
    expect(existsSync(join(root, '.golive/handover.json'))).toBe(false);

    mkdirSync(join(root, '.golive'), { recursive: true });
    writeFileSync(join(root, '.golive/handover.json'), '{"not":"ours"}');
    rmSync(join(root, 'GOLIVE_HANDOVER.md'));
    const refusedJson = await runCli(root, ['handoff', '--write']);
    expect(refusedJson.code).toBe(1);
    expect(JSON.parse(refusedJson.output).error.message).toMatch(/handover\.json exists and carries no "Generated by golive" marker/);
    expect(readFileSync(join(root, '.golive/handover.json'), 'utf8')).toBe('{"not":"ours"}');
  });

  it('replaces a foreign file only with --force, and never touches HANDOFF.local.md', async () => {
    writeFileSync(join(root, 'GOLIVE_HANDOVER.md'), 'my own private notes\n');
    const foreign = join(root, 'HANDOFF.local.md');
    writeFileSync(foreign, 'private local agent notes\n');
    const forced = await runCli(root, ['handoff', '--write', '--force']);
    expect(forced.code).toBe(0);
    expect(readFileSync(join(root, 'GOLIVE_HANDOVER.md'), 'utf8')).toContain('Generated by golive');
    expect(readFileSync(foreign, 'utf8')).toBe('private local agent notes\n');
    expect(existsSync(join(root, 'HANDOFF.local.json'))).toBe(false);
  });

  it('names the new files in help', async () => {
    const result = await runCli(root, ['help']);
    expect(result.output).toContain('.golive/handover.json and GOLIVE_HANDOVER.md');
    expect(existsSync(join(root, 'GOLIVE_HANDOVER.md'))).toBe(false);
  });
});
