/**
 * Issue #65: on a host whose CLI uploads the deploy folder (`vercel deploy`), golive's own files —
 * `.golive/state.json`, `golive.yaml`, the report and handover documents, the run docs — would be
 * served publicly unless the host's ignore file excludes them. The upload link plans that exclusion
 * as a local file edit, and the deploy link treats it as a reason to redeploy (an upload only changes
 * with a new deployment).
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { buildPlan, planView } from '../src/core/plan.js';
import { applyPlan } from '../src/core/runner.js';
import { uploadLink } from '../src/links/upload.js';
import { deployLink } from '../src/links/deploy.js';
import { resetMemo } from '../src/links/util.js';
import type { Adapter, Check, Ctx, DetectResult, UploadRules } from '../src/core/types.js';
import { testCtx } from './helpers.js';

const IGNORE = '.vercelignore';
const MARKER = '# golive: keep its own files (state, config, reports, run docs) out of this upload';

let cwd: string;
beforeEach(() => {
  cwd = mkdtempSync(join(tmpdir(), 'golive-upload-'));
});
afterEach(() => {
  rmSync(cwd, { recursive: true, force: true });
});

/** The files golive leaves in a repo after a run, as the walkthrough repo had them. */
function repo(extra: Record<string, string> = {}): void {
  const files = {
    '.golive/state.json': '{"version":1,"resources":{"vercel.projectId":"prj_1"},"secrets":{},"steps":{}}',
    'golive.yaml': 'version: 1\nstack:\n  hosting: vercel\n',
    'GOLIVE_REPORT.md': '# Ship report\n\nGenerated by golive. This file contains no secrets.\n',
    ...extra,
  };
  for (const [rel, content] of Object.entries(files)) {
    mkdirSync(dirname(join(cwd, rel)), { recursive: true });
    writeFileSync(join(cwd, rel), content);
  }
}

function host(upload: UploadRules | false = { ignoreFile: IGNORE, servesFolder: () => true }): Adapter {
  let deploys = 0;
  return {
    id: 'fakehost',
    title: 'FakeHost',
    axes: ['hosting'],
    automated: true,
    auth: async () => ({ ok: true, via: 'same user' }),
    capabilities: {
      url: { get: async () => 'https://shop.fakehost.app' },
      deploy: {
        deploy: async () => {
          deploys++;
          return { url: 'https://shop-abc.fakehost.app', id: 'dpl_1' };
        },
      },
      ...(upload ? { upload } : {}),
    },
  } as Adapter & { deploys?: number };
}

function build(upload: UploadRules | false = { ignoreFile: IGNORE, servesFolder: () => true }) {
  const ctx = testCtx({
    cwd,
    adapters: [host(upload)],
    config: { stack: { hosting: 'fakehost' }, domain: undefined },
    detect: { framework: 'static' } as Partial<DetectResult>,
  });
  resetMemo(ctx);
  return { ctx, built: buildPlan(ctx, [uploadLink, deployLink], { unmappedEnv: [], warnings: [] }) };
}

const apply = (ctx: Ctx, plan: Awaited<ReturnType<typeof buildPlan>>, checks: Map<string, Check> = new Map()) =>
  applyPlan(ctx, plan, checks, { approvedPlanId: plan.id, yes: true, confirmLive: true, confirmDns: false });

const VERCEL_LIKE: UploadRules = { ignoreFile: IGNORE, conflicting: ['.nowignore'], servesFolder: () => true };

describe('upload:excludes', () => {
  it('plans the exclusion, names every line in the preview, and makes the deploy wait for it', async () => {
    repo();
    const { built } = build();
    const plan = await built;
    expect(plan.steps.map((s) => s.id)).toEqual(['upload:excludes', 'deploy:production']);
    const step = plan.steps[0]!;
    expect(step.risk).toEqual({ writes: false });
    const preview = step.preview.join('\n');
    expect(preview).toContain(`append golive's block to ${IGNORE} (a local file in this repo; nothing is written at FakeHost`);
    expect(preview).toContain('.golive/state.json, golive.yaml, GOLIVE_REPORT.md');
    expect(preview).toContain('would be publicly fetchable');
    for (const line of ['.golive/', 'golive.yaml', 'GOLIVE_REPORT.md', 'GOLIVE_HANDOVER.md', 'SHIP_REPORT.md', 'docs/GOLIVE-*']) {
      expect(preview).toContain(`+ ${line}`);
    }
    const deploy = plan.steps[1]!;
    expect(deploy.dependsOn).toContain('upload:excludes');
    // The deploy picks the exclusion up: its intent names the step and its content.
    expect(deploy.intent).toContain('upload:excludes#');
    expect(deploy.preview.join('\n')).toContain("so golive's own files leave the upload (upload:excludes)");
  });

  it('writes the block once and stops planning it afterwards', async () => {
    repo();
    const { ctx, built } = build();
    const plan = await built;
    const out = await apply(ctx, plan);
    expect(out).toHaveLength(2);
    expect(existsSync(join(cwd, IGNORE))).toBe(true);
    expect(readFileSync(join(cwd, IGNORE), 'utf8')).toContain(MARKER);
    expect(readFileSync(join(cwd, IGNORE), 'utf8')).toContain('docs/GOLIVE-*');

    resetMemo(ctx);
    const again = await buildPlan(ctx, [uploadLink, deployLink], { unmappedEnv: [], warnings: [] });
    // Nothing else needs a deployment: the block is in place, so no step — and the steady-state
    // warning says where a code change ships instead.
    expect(again.steps.map((s) => s.id)).toEqual([]);
    expect(again.warnings.join('\n')).toContain('no production deploy is planned');
  });

  it('keeps an existing allowlist exactly as it is, and appends golive\u2019s block below it', async () => {
    repo();
    const allowlist = '/*\n!api\n!index.html\n!vercel.json\n';
    writeFileSync(join(cwd, IGNORE), allowlist);
    const { ctx, built } = build();
    const plan = await built;
    await apply(ctx, plan);
    const text = readFileSync(join(cwd, IGNORE), 'utf8');
    expect(text.startsWith(allowlist)).toBe(true);
    expect(text).toContain(MARKER);
    expect(text).toContain('.golive/');
  });

  it('plans nothing for a framework build, where the served site is the build output', async () => {
    repo();
    const ctx = testCtx({ cwd, adapters: [host({ ignoreFile: IGNORE, servesFolder: () => false })], config: { stack: { hosting: 'fakehost' }, domain: undefined } });
    resetMemo(ctx);
    expect(await uploadLink.plan(ctx)).toBeNull();
  });

  it('plans nothing without a host that uploads the folder, or without any golive file in the repo', async () => {
    repo();
    const plain = testCtx({ cwd, adapters: [host(false)], config: { stack: { hosting: 'fakehost' }, domain: undefined } });
    resetMemo(plain);
    expect(await uploadLink.plan(plain)).toBeNull();

    rmSync(join(cwd, '.golive'), { recursive: true, force: true });
    rmSync(join(cwd, 'golive.yaml'));
    rmSync(join(cwd, 'GOLIVE_REPORT.md'));
    const { ctx } = build();
    expect(await uploadLink.plan(ctx)).toBeNull();
  });

  it('never creates a combination the host CLI refuses: a legacy .nowignore means no step, with the reason', async () => {
    repo();
    writeFileSync(join(cwd, '.nowignore'), 'legacy\n');
    const { built } = build(VERCEL_LIKE);
    const plan = await built;
    expect(plan.steps.some((s) => s.id === 'upload:excludes')).toBe(false);
    expect(plan.warnings.join('\n')).toContain(`golive did not add ${IGNORE}`);
    expect(plan.warnings.join('\n')).toContain('.nowignore');
    expect(existsSync(join(cwd, IGNORE))).toBe(false);
  });

  it('fails the step, with what to do by hand, when the file cannot be written', async () => {
    repo();
    mkdirSync(join(cwd, IGNORE)); // a directory where the ignore file belongs: the write cannot succeed
    const { ctx, built } = build();
    const plan = await built;
    const out = await apply(ctx, plan);
    expect(out[0]).toMatchObject({ id: 'upload:excludes', status: 'failed' });
    expect(out[0]!.error).toContain(`could not write ${IGNORE}`);
    expect(out[0]!.error).toContain(MARKER);
    // The deploy waited for it and did not run.
    expect(out.map((o) => o.id)).toEqual(['upload:excludes']);
  });

  it('is listed in the approval view with the file it edits', async () => {
    repo();
    const { built } = build();
    const view = planView(await built);
    expect(view.steps[0]).toMatchObject({ id: 'upload:excludes', kind: 'provision', writes: false });
  });
});
