// Bundle src/cli.ts into ONE zero-dependency ESM file shipped inside the skill folder.
import { build } from 'esbuild';
import { copyFileSync } from 'node:fs';
import { buildRelease } from './scripts/build-release.mjs';

await build({
  entryPoints: ['src/cli.ts'],
  outfile: 'skills/golive/scripts/golive.mjs',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  minify: false, // keep it readable: users should be able to audit what touches their accounts
  legalComments: 'none',
  banner: {
    js: [
      '#!/usr/bin/env node',
      '// golive — generated by build.mjs from src/. Do not edit by hand.',
      // Bundled CommonJS deps (yaml) call require() for Node builtins; give ESM a real require.
      "import { createRequire as __goliveCreateRequire } from 'node:module';",
      'const require = __goliveCreateRequire(import.meta.url);',
    ].join('\n'),
  },
});
console.log('built skills/golive/scripts/golive.mjs');
// The owned installer runs independently of the application CLI, with zero dependencies.
for (const helper of ['install-lib.mjs', 'install-cli.mjs']) {
  copyFileSync(`scripts/${helper}`, `skills/golive/scripts/${helper}`);
}
buildRelease();
console.log('built skills/golive/release.json');
