import type { CheckResult, Report } from '../core/types.js';

const ICON: Record<CheckResult['status'], string> = { pass: '✅', fail: '❌', warn: '⚠️', skip: '⏭️' };
const ORDER: CheckResult['status'][] = ['fail', 'warn', 'pass', 'skip'];

/** GOLIVE_REPORT.md — human-readable, secret-free (built only from the already-redacted report). */
export function renderReport(r: Report): string {
  const lines: string[] = [];
  const verdict =
    r.summary.fail > 0
      ? `${r.summary.fail} check(s) failing.`
      : r.summary.blocking > 0
        ? 'Verification incomplete: some human steps are still open.'
        : r.summary.manual > 0
          ? 'Verification incomplete: some steps could not be verified by golive — confirm them by hand.'
          : r.checks.length === 0
            ? 'No checks ran.'
            : r.summary.warn > 0
              ? 'Verification completed with warnings.'
              : r.summary.skip > 0
                ? 'Verification completed with skipped checks.'
                : r.verification?.scope === 'partial'
                  ? 'Selected checks passed.'
                  : 'Checks passed in this invocation.';
  lines.push('# Ship report', '', `_${r.generatedAt}_ · ${verdict}`, '');
  if (r.release) lines.push(`Release: \`${r.release.name}@${r.release.version}\` · bundle \`${r.release.bundleDigest}\``, '');
  if (r.verification) {
    lines.push(`Verification scope: **${r.verification.scope === 'partial' ? 'selected checks only' : 'all registered checks'}**.`, '');
    if (r.verification.scope === 'partial') lines.push(`Requested: ${r.verification.requestedCheckIds.map((id) => `\`${id}\``).join(', ') || '(none)'}.`, `Not run in this invocation: ${r.verification.omittedCheckIds.map((id) => `\`${id}\``).join(', ')}.`, '');
  }
  lines.push('Deployment readiness is not established by this report. Review the current plan for pending steps and verify the application flows.', '');

  const urls = Object.entries(r.app.urls);
  if (urls.length) {
    lines.push('## Live', '');
    for (const [t, u] of urls) lines.push(`- **${t}**: ${u}`);
    lines.push('');
  }

  const stack = Object.entries(r.stack);
  if (stack.length) lines.push('## Stack', '', stack.map(([a, p]) => `\`${a}\`: ${p}`).join(' · '), '');

  lines.push('## Checks', '', `${r.summary.pass} passed · ${r.summary.fail} failed · ${r.summary.warn} warnings · ${r.summary.skip} skipped`, '');
  const sorted = [...r.checks].sort((a, b) => ORDER.indexOf(a.status) - ORDER.indexOf(b.status));
  for (const c of sorted) {
    lines.push(`### ${ICON[c.status]} ${c.title}`, '');
    if (c.status !== 'pass' && c.status !== 'skip') lines.push(`Severity: **${c.severity}**`, '');
    for (const e of c.evidence) lines.push(`- ${e}`);
    if (c.fix && c.status !== 'pass') lines.push('', `**Fix:** ${c.fix}`);
    lines.push('');
  }

  const open = r.handoffs.filter((h) => h.done !== true);
  if (open.length) {
    lines.push('## Needs you', '');
    for (const h of open) {
      const tag = h.done === null ? '**[not verifiable by golive]** ' : h.blocking ? '**[blocking]** ' : '';
      lines.push(`- ${tag}${h.action}${h.url ? ` (${h.url})` : ''}`, `  - Why: ${h.why}`);
    }
    lines.push('');
  }
  const done = r.handoffs.filter((h) => h.done === true);
  if (done.length) lines.push('## Done by you (verified)', '', ...done.map((h) => `- ✅ ${h.action}`), '');
  lines.push('---', 'Generated by golive. This file contains no secrets.');
  return lines.join('\n') + '\n';
}
