import type { Check, Ctx } from '../core/types.js';
import { goliveRepoFiles } from '../core/artifacts.js';
import { cap, confirmedProductionUrl, errMsg, pass, probe, result, skip, trimSlash } from './util.js';

/**
 * How a served body proves it is the file and not the app's own routing answering a catch-all (a SPA
 * answers 200 HTML for any path, which is a pass with that note, never a finding). Returns what was
 * recognised, or null.
 */
function identifies(file: string, body: string): string | null {
  const head = body.slice(0, 4_000);
  if (file.endsWith('.json')) {
    let json: unknown;
    try {
      json = JSON.parse(head);
    } catch {
      return null;
    }
    if (!json || typeof json !== 'object') return null;
    const keys = json as Record<string, unknown>;
    if ('resources' in keys && 'steps' in keys) return 'the state file (.golive/state.json: resources + steps)';
    if ('checks' in keys && 'summary' in keys) return 'the verify report (.golive/report.json: checks + summary)';
    if ('runbook' in keys && 'retirement' in keys) return 'the ownership document (.golive/handover.json: runbook + retirement)';
    return null;
  }
  if (/\.ya?ml$/i.test(file)) {
    return /(^|\n)version:\s*1\s*(\n|$)/.test(head) && /(^|\n)stack:/.test(head) ? 'the golive.yaml config (version + stack)' : null;
  }
  if (/\.md$/i.test(file)) {
    if (head.includes('Generated by golive')) return 'a golive document (its "Generated by golive" marker)';
    // An agent-written run document carries no golive marker; markdown served where the app would
    // answer HTML counts as the file itself.
    return /^\s*#{1,2}\s/.test(head) && !/<html[\s>]/i.test(head) ? 'a markdown document served as-is (the app would answer HTML here)' : null;
  }
  return null;
}

/**
 * What to do about files that are served: the host's own ignore file when it has one, otherwise the
 * setting that decides what the host publishes.
 */
function fixFor(ctx: Ctx): string {
  const rules = cap(ctx, 'hosting', 'upload');
  const where = rules
    ? `add them to ${rules.ignoreFile} in this repo (golive plans that as \`upload:excludes\`)`
    : "take them out of the directory this host publishes (its publish/output setting, or its ignore file if it has one)";
  return `Keep golive's own files out of the deployment and deploy again: ${where} — .golive/, golive.yaml, GOLIVE_REPORT.md, GOLIVE_HANDOVER.md and docs/GOLIVE-* — then re-run \`verify\`.`;
}

/**
 * Reads the live production site for the files golive writes into this repo. A host whose CLI uploads
 * the deploy folder (`vercel deploy`) serves what it uploaded, so `.golive/state.json` (team/project
 * ids, account name), `golive.yaml` and the run documents can be publicly fetchable (issue #65). Only
 * a body that IS the file fails: a 404 is a pass, a 401/403 skips (a private deployment is not
 * evidence), and the app's own catch-all answering 200 is named as such. Nothing is written.
 */
export const uploadExposureCheck: Check = {
  id: 'upload-exposure',
  title: "Production does not serve golive's own state, config or reports",
  severity: 'high',
  applies: () => true,
  async run(ctx) {
    const confirmed = await confirmedProductionUrl(ctx);
    if (!confirmed.ok) return confirmed.outcome;
    const files = goliveRepoFiles(ctx.cwd);
    if (!files.length) return skip("no .golive state, golive.yaml or run document exists in this repo — and the check reads the folder golive runs in — so there is nothing of golive's to serve");
    const base = trimSlash(confirmed.url);
    const evidence: string[] = [];
    const served: string[] = [];
    const unreadable: string[] = [];
    for (const file of files) {
      const url = `${base}/${file}`;
      let res;
      try {
        res = await probe(ctx, url, { headers: { 'user-agent': 'golive-verify' }, timeoutMs: 15_000 });
      } catch (e) {
        unreadable.push(`${file} (${errMsg(e)})`);
        continue;
      }
      const got = `GET ${url} → HTTP ${res.status}`;
      if (res.status === 401 || res.status === 403) {
        return skip(`${got}: production may be private (visitor access, SSO or an auth wall answering anonymous requests), so what it serves was not read`);
      }
      if (res.status === 404 || res.status === 410) {
        evidence.push(`${got} (not served)`);
        continue;
      }
      if (res.status !== 200) {
        evidence.push(`${got}: an unexpected status, so this path is not read as served`);
        continue;
      }
      const what = identifies(file, res.text ?? '');
      if (what) served.push(`${file} (${what})`);
      else evidence.push(`${got}: the body is not ${file} — the app's own routing answered, so no golive content was read`);
    }
    if (served.length) return result('fail', 'high', [...evidence, `publicly fetchable: ${served.join('; ')}`], fixFor(ctx));
    if (unreadable.length) {
      return result('warn', 'medium', [...evidence, `could not read: ${unreadable.join(', ')} — not evidence either way`], fixFor(ctx));
    }
    return pass(evidence);
  },
};
