/**
 * The handover document's data: what the owner of this app needs to know now that golive shipped it.
 *
 * Every row says where its claim comes from: a provider read golive made just now (auth, project and
 * URL reads, the teardown inventory), recorded state (`resources` and step records), `golive.yaml`,
 * or a plan handoff whose check already ran. `state.secrets` and every `Outputs` VALUE are excluded
 * by construction — only names, ids, fingerprints and URLs reach the document. Nothing here writes,
 * calls a billing endpoint, or states a cost golive did not read.
 */
import { AXES, type Axis, type Ctx, type EnvTarget, type HandoffItem, type ProjectRef } from '../core/types.js';
import { adapterById, adapterFor } from '../core/caps.js';
import { buildInventory, createdProjectKey, projectStateKeys, type Inventory } from '../core/inventory.js';
import { errMsg, hostUrl, repoName } from '../links/util.js';
import { GUIDED } from '../adapters/guided.js';

/** The marker every golive-generated file carries; an existing file without it is never overwritten. */
export const HANDOVER_MARKER = 'Generated by golive';

/** How a row's claim can be checked. Rendered in the document by `src/report/handover.ts`. */
export type Provenance =
  | { kind: 'verified' }
  | { kind: 'recorded'; at?: string }
  | { kind: 'unverifiable' }
  | { kind: 'unknown' };

export interface HandoverAccount {
  axis: Axis;
  provider: string;
  providerTitle: string;
  /** How golive reaches the account now, from the provider's own auth check. */
  via?: string;
  /**
   * The team/organization display name a read returned. Always present: a provider that reported
   * none is stated as such, because an empty cell reads as "there is no account at all".
   */
  account: string;
  /** What the human does to log in (or back in). */
  login: string;
  provenance: Provenance;
}

export interface HandoverResource {
  axis: Axis;
  provider: string;
  providerTitle: string;
  /** What the resource is, e.g. "host project", "DNS record", "webhook endpoint". */
  kind: string;
  name: string;
  /** The provider's id for it, or the record's value when the provider has no id for it. */
  id: string;
  url?: string;
  /** Whether golive created it; an adopted resource is recorded but never claimed as golive's. */
  ownership: 'created' | 'adopted';
  /** Why golive says so — the ownership proof, not a guess. */
  proof: string;
  /** Whether an approved teardown can remove it. */
  removable: boolean;
  provenance: Provenance;
}

export interface HandoverCost {
  provider: string;
  providerTitle: string;
  /** What golive read about the plan, quota or usage — today: nothing. */
  read: string;
  /** Where the provider's own numbers live. */
  where: string;
  provenance: Provenance;
}

export interface HandoverManual {
  kind: 'handoff' | 'recurring';
  title: string;
  action: string;
  why?: string;
  url?: string;
  /** A blocking handoff is one that keeps the app from working. */
  blocking?: boolean;
  provenance: Provenance;
}

export interface HandoverRunbook {
  subject: string;
  commands: string[];
  note: string;
}

export interface HandoverRetirement {
  resource: string;
  /** What removes it, and under which confirmation gates. */
  how: string;
  removable: boolean;
  provenance: Provenance;
}

export interface HandoverSectionProvenance {
  section: string;
  source: string;
  at: string;
  tags: Provenance['kind'][];
}

export interface HandoverDoc {
  version: 1;
  /** The "Generated by golive" marker, also carried by the JSON file the CLI writes. */
  generator: string;
  generatedAt: string;
  release: { name: string; version: string; bundleDigest: string; ref: string | null };
  product: { name: string; root: string; framework: string; domain?: string };
  /** URLs the hosting provider itself reported in this run. */
  urls: Partial<Record<EnvTarget, string>>;
  /** One-line limits a reader must keep in mind. */
  limits: string[];
  accounts: HandoverAccount[];
  resources: HandoverResource[];
  costs: HandoverCost[];
  /** Open handoffs (still the human's) plus the jobs that come back. */
  manual: HandoverManual[];
  /** Handoffs a passing check already closed in this run. */
  manualClosed: number;
  runbook: HandoverRunbook[];
  /** Where the evidence behind every claim lives. */
  evidence: string[];
  retirement: HandoverRetirement[];
  provenance: HandoverSectionProvenance[];
}

export interface HandoverInput {
  /** Handoffs with their status, exactly as the `handoff` command computed them. */
  handoffs: Array<HandoffItem & { done: boolean | null; evidence: string[] }>;
  /** Registered checks with the applicability their own `applies()` reported for this stack. */
  checks: readonly HandoverCheck[];
}

/** A check this release registers, and whether its own predicate says this stack ever runs it. */
export interface HandoverCheck {
  id: string;
  /**
   * False when the check's predicate says it skips this stack — the Netlify visibility check on a
   * Vercel app, a domain check with no domain configured — so a runbook must not name it.
   */
  applies: boolean;
}

/**
 * Which checks cover each axis. A runbook line only names ids this release registers *and* this stack
 * runs, so a provider is never handed another provider's check.
 */
const AXIS_CHECKS: Record<Axis, string[]> = {
  hosting: ['domain-live', 'env-parity', 'netlify-public-access', 'bundle-secrets'],
  db: ['db-connection', 'rls-probe'],
  auth: ['auth-redirects'],
  payments: ['webhook-registered', 'webhook-unsigned', 'stripe-live-ready'],
  email: ['email-dns', 'email-verified'],
  dns: ['domain-live'],
  monitoring: [],
};

/** Where each provider's own cost facts live. golive reads no usage, invoice or quota data. */
const BILLING: Record<string, string> = {
  vercel: 'the Usage and Billing pages of your Vercel dashboard',
  netlify: 'your Netlify team dashboard → Usage & billing',
  supabase: 'your Supabase organization settings → Billing',
  neon: 'the Billing page of the Neon console',
  stripe: 'your Stripe account settings → Billing, and the published per-transaction fees',
  resend: 'your Resend account → Billing',
  cloudflare: 'your Cloudflare account → Billing',
  godaddy: 'your GoDaddy account → Subscriptions and renewals',
  porkbun: 'your Porkbun account → domain pricing and renewals',
};

/** State keys that recorded each resource, so a "recorded" row can name the step's own timestamp. */
const RECORDING_STEP = {
  webhook: ['payments:webhook:production'],
  project: ['project:hosting'],
  database: ['project:db'],
  domain: ['email:domain'],
} satisfies Record<string, string[]>;

/**
 * Build the handover document. Read-only: the provider reads are the same cheap ones `doctor` and
 * `verify` already make, plus the teardown inventory.
 */
export async function buildHandover(ctx: Ctx, input: HandoverInput): Promise<HandoverDoc> {
  const generatedAt = new Date().toISOString();
  const inventory = await buildInventory(ctx);
  const projects = await currentProjects(ctx);
  const accounts = await accountRows(ctx, projects);
  const urls = await liveUrls(ctx);
  const resources = resourceRows(ctx, inventory, projects, urls);
  const manual = manualRows(ctx, input.handoffs);
  return {
    version: 1,
    generator: HANDOVER_MARKER,
    generatedAt,
    release: { name: ctx.release.name, version: ctx.release.version, bundleDigest: ctx.release.bundleDigest, ref: ctx.release.source.ref },
    product: { name: repoName(ctx), root: ctx.cwd, framework: ctx.detect.framework, ...(ctx.config.domain ? { domain: ctx.config.domain } : {}) },
    urls,
    limits: limits(ctx, input),
    accounts,
    resources,
    costs: costRows(ctx),
    manual,
    manualClosed: input.handoffs.filter((h) => h.done === true).length,
    runbook: runbookRows(ctx, input.checks),
    evidence: [
      '.golive/state.json — resource ids, fingerprints and per-step records (no values)',
      '.golive/report.json and GOLIVE_REPORT.md — the last `verify` results, check by check',
      'GOLIVE_HANDOVER.md and .golive/handover.json — this document',
      'golive.yaml — provider choices and non-secret configuration',
    ],
    retirement: retirementRows(ctx, inventory),
    provenance: provenanceRows(generatedAt, resources),
  };
}

// ── Header ──────────────────────────────────────────────────────────────────────────────────────

function limits(ctx: Ctx, input: HandoverInput): string[] {
  const open = input.handoffs.filter((h) => h.done !== true).length;
  const stack = axesUsed(ctx).map((a) => `${a.axis}: ${a.provider}`).join(', ');
  return [
    'Rows tagged [verified by golive] were read in this run; every other row is a recording, and this document is not drift detection.',
    open
      ? `${open} handoff(s) are still the human's. Verification checks cover infrastructure, not the app's own flows.`
      : "No handoff is open. Verification checks still cover infrastructure, not the app's own flows.",
    'It contains no secret values — but secret-free metadata can still identify private resources, so review it before sharing it.',
    `Scope: the providers in golive.yaml (${stack || 'none'}); other frameworks, pairings and app-level flows are outside what golive validated.`,
  ];
}

// ── Accounts ────────────────────────────────────────────────────────────────────────────────────

/** The project each axis is linked to, read once: the provider's own cheap `current()` read. */
async function currentProjects(ctx: Ctx): Promise<Map<Axis, ProjectRef | null>> {
  const out = new Map<Axis, ProjectRef | null>();
  const seen = new Map<string, Promise<ProjectRef | null>>();
  for (const axis of ['hosting', 'db'] as Axis[]) {
    const adapter = adapterFor(ctx, axis);
    const linker = adapter?.capabilities.project;
    if (!adapter || !linker) continue;
    let read = seen.get(adapter.id);
    if (!read) {
      read = linker.current(ctx).catch(() => null);
      seen.set(adapter.id, read);
    }
    out.set(axis, await read);
  }
  return out;
}

/**
 * The account cell of the login table. A provider that named no team/account is said to have named
 * none — the column is never left blank, which would read as "there is no account".
 */
const NO_ACCOUNT = 'not reported by the provider';

async function accountRows(ctx: Ctx, projects: Map<Axis, ProjectRef | null>): Promise<HandoverAccount[]> {
  const rows: HandoverAccount[] = [];
  for (const axis of AXES) {
    const id = ctx.config.stack[axis];
    if (!id) continue;
    const adapter = adapterById(id, ctx.adapters);
    const providerTitle = adapter?.title ?? GUIDED.find((g) => g.id === id)?.title ?? id;
    const project = projects.get(axis);
    const account = project?.scope?.name ?? project?.scope?.id ?? NO_ACCOUNT;
    if (!adapter || !adapter.automated) {
      rows.push({
        axis,
        provider: id,
        providerTitle,
        account,
        login: `guided provider: golive has no adapter for it, so confirm the ${providerTitle} account with the human in its dashboard`,
        provenance: { kind: 'unverifiable' },
      });
      continue;
    }
    let via: string | undefined;
    let login: string;
    let provenance: Provenance = { kind: 'verified' };
    try {
      const status = await adapter.auth(ctx);
      via = status.via;
      login = status.ok
        ? `connected — if access expires: ${status.howToFix ?? `sign in to ${providerTitle} again, in a separate terminal window`}`
        : (status.howToFix ?? `sign in to ${providerTitle} again, in a separate terminal window`);
    } catch (e) {
      // A failed read is not a logout: say what golive could not check instead of guessing.
      login = `golive could not check the ${providerTitle} login (${errMsg(e)}); run \`doctor\` after fixing access`;
      provenance = { kind: 'unknown' };
    }
    rows.push({ axis, provider: id, providerTitle, ...(via ? { via } : {}), account, login, provenance });
  }
  return rows;
}

async function liveUrls(ctx: Ctx): Promise<Partial<Record<EnvTarget, string>>> {
  const out: Partial<Record<EnvTarget, string>> = {};
  for (const target of ctx.config.targets) {
    const url = await hostUrl(ctx, target);
    if (url) out[target] = url;
  }
  return out;
}

// ── Resources ───────────────────────────────────────────────────────────────────────────────────

function resourceRows(ctx: Ctx, inventory: Inventory, projects: Map<Axis, ProjectRef | null>, urls: Partial<Record<EnvTarget, string>>): HandoverResource[] {
  const rows: HandoverResource[] = [];

  // Read from the DNS provider in this run: the provider itself says these records are golive-owned.
  for (const r of inventory.dnsRecords) {
    rows.push({
      axis: 'dns',
      provider: r.provider,
      providerTitle: r.providerTitle,
      kind: 'DNS record',
      name: `${r.record.type} ${r.record.name}`,
      id: r.record.content,
      ownership: 'created',
      proof: `${r.providerTitle} lists it as golive-owned (the provider's marker or a fingerprint golive recorded)`,
      removable: true,
      provenance: { kind: 'verified' },
    });
  }

  for (const w of inventory.webhooks) {
    rows.push({
      axis: 'payments',
      provider: w.provider,
      providerTitle: w.providerTitle,
      kind: 'webhook endpoint',
      name: `${w.providerTitle} ${w.mode}-mode webhook endpoint`,
      id: w.id,
      ownership: 'created',
      proof: `recorded in state as the endpoint golive registered (${w.key})`,
      removable: Boolean(w.removal),
      provenance: { kind: 'recorded', at: recordedAt(ctx, RECORDING_STEP.webhook) },
    });
  }

  for (const k of inventory.sendingKeys) {
    rows.push({
      axis: 'email',
      provider: k.provider,
      providerTitle: k.providerTitle,
      kind: 'sending key',
      name: `${k.providerTitle} sending key for ${k.target}`,
      id: k.id,
      ownership: 'created',
      proof: `recorded in state as the key golive issued (${k.key}); only its fingerprint is stored`,
      removable: Boolean(k.revocation),
      provenance: { kind: 'recorded', at: recordedAt(ctx, [`email:key:${k.target}`]) },
    });
  }

  const host = adapterFor(ctx, 'hosting');
  if (host) {
    const keys = projectStateKeys(host.id);
    const id = ctx.state.resource(keys.id);
    if (id) {
      const current = projects.get('hosting');
      const created = ctx.state.resource(createdProjectKey(host.id)) === id;
      const live = current?.id === id;
      rows.push({
        axis: 'hosting',
        provider: host.id,
        providerTitle: host.title,
        kind: 'host project',
        name: ctx.state.resource(keys.name) ?? current?.name ?? id,
        id,
        // A URL is only reported when the host itself confirmed this exact project in this run.
        ...(live && urls.production ? { url: urls.production } : {}),
        ownership: created ? 'created' : 'adopted',
        proof: created
          ? `state's creation marker (${createdProjectKey(host.id)}) names this project, so golive created it`
          : 'state links this project but holds no creation marker for it, so golive adopted it and never claims it',
        removable: Boolean(created && inventory.project),
        provenance: live ? { kind: 'verified' } : { kind: 'recorded', at: recordedAt(ctx, RECORDING_STEP.project) },
      });
    }
  }

  for (const r of inventory.recorded) {
    const subject = r.kind === 'database-project' ? 'database project' : 'sending domain';
    rows.push({
      axis: r.axis,
      provider: r.provider,
      providerTitle: r.providerTitle,
      kind: subject,
      name: r.name,
      id: r.id,
      ownership: r.created ? 'created' : 'adopted',
      proof: r.created
        ? `${r.providerTitle} has no creation marker to read; state records this id as the ${subject} golive created (${r.key})`
        : `state records this ${subject} (${r.key}) without golive's creation marker, so golive does not claim it`,
      removable: false, // no provider capability: removal is a manual handoff
      provenance: { kind: 'recorded', at: recordedAt(ctx, r.kind === 'database-project' ? RECORDING_STEP.database : RECORDING_STEP.domain) },
    });
  }

  return rows;
}

/**
 * When state recorded a resource: the timestamp of the step that recorded it, or of the newest
 * recorded step when that step ran under a different id. Undefined when state holds no step at all.
 */
function recordedAt(ctx: Ctx, stepIds: readonly string[]): string | undefined {
  const steps = ctx.state.get().steps;
  for (const id of stepIds) {
    const at = steps[id]?.at;
    if (at) return at;
  }
  return Object.values(steps).map((r) => r.at).sort().at(-1);
}

// ── Costs ───────────────────────────────────────────────────────────────────────────────────────

function costRows(ctx: Ctx): HandoverCost[] {
  const byProvider = new Map<string, HandoverCost>();
  for (const { provider, providerTitle } of axesUsed(ctx)) {
    // One row per provider: an axis can share a provider (Supabase serves db and auth).
    if (byProvider.has(provider)) continue;
    byProvider.set(provider, {
      provider,
      providerTitle,
      read: 'nothing: golive does not read plans, quotas, usage or invoices, and never calls a billing endpoint',
      where: billingOf(provider, providerTitle),
      provenance: { kind: 'unknown' },
    });
  }
  return [...byProvider.values()];
}

function billingOf(provider: string, providerTitle: string): string {
  return BILLING[provider] ?? `the billing/usage page of your ${providerTitle} account`;
}

// ── What is manual ──────────────────────────────────────────────────────────────────────────────

function manualRows(ctx: Ctx, handoffs: HandoverInput['handoffs']): HandoverManual[] {
  const open = handoffs.filter((h) => h.done !== true).map((h): HandoverManual => ({
    kind: 'handoff',
    title: h.id,
    action: h.action,
    why: h.why,
    ...(h.url ? { url: h.url } : {}),
    blocking: h.blocking,
    // done:null cannot be verified by golive at all; done:false means its own check ran and did not pass.
    provenance: h.done === null ? { kind: 'unverifiable' } : { kind: 'verified' },
  }));
  const used = new Set(axesUsed(ctx).map((a) => a.axis));
  const recurring: HandoverManual[] = [];
  if (used.has('email')) {
    recurring.push({
      kind: 'recurring',
      title: 'email: tighten DMARC once the domain has sending history',
      action: 'Keep the SPF and DKIM records as they are, and tighten the domain\'s DMARC policy toward quarantine/reject as reputation builds',
      why: 'a fresh sending domain lands in spam without DMARC; golive publishes the provider\'s records but does not manage DMARC',
      provenance: { kind: 'unverifiable' },
    });
  }
  if (used.has('payments') || used.has('email')) {
    recurring.push({
      kind: 'recurring',
      title: 'keys: rotate the provider keys the app uses',
      action: 'Rotate the app\'s provider keys on your own schedule, then re-run `golive plan` so any env write golive manages is refreshed',
      why: 'nothing expires these keys for you; golive stores fingerprints only, so it can never show you the old value',
      provenance: { kind: 'unverifiable' },
    });
  }
  if (used.has('db')) {
    recurring.push({
      kind: 'recurring',
      title: 'database: back up, and drill a restore',
      action: 'Confirm the database provider\'s backup retention, and restore into a scratch project at least once',
      why: 'golive does not manage backups or restores; `teardown` deletes resources rather than protecting them',
      provenance: { kind: 'unverifiable' },
    });
  }
  if (ctx.config.domain) {
    recurring.push({
      kind: 'recurring',
      title: `domain: renew ${ctx.config.domain} at its registrar`,
      action: `Renew ${ctx.config.domain} before it expires, and keep the registrar account reachable`,
      why: 'golive never buys, transfers or renews domains',
      provenance: { kind: 'unverifiable' },
    });
  }
  return [...open, ...recurring];
}

// ── Runbook ─────────────────────────────────────────────────────────────────────────────────────

function runbookRows(ctx: Ctx, checks: readonly HandoverCheck[]): HandoverRunbook[] {
  const registered = new Set(checks.map((c) => c.id));
  // Only checks this release registers and this stack actually runs: a Vercel owner is never handed
  // the Netlify visibility check, and a stack with no domain is not told to re-read the domain.
  const runs = new Set(checks.filter((c) => c.applies).map((c) => c.id));
  const rows: HandoverRunbook[] = [];
  for (const { axis, providerTitle } of axesUsed(ctx)) {
    const offered = AXIS_CHECKS[axis].filter((id) => registered.has(id));
    const ids = offered.filter((id) => runs.has(id));
    rows.push({
      subject: `${axis} (${providerTitle})`,
      commands: ['golive doctor', ...(ids.length ? [`golive verify --only ${ids.join(',')}`] : [])],
      note: ids.length
        ? `re-reads ${ids.join(', ')}; evidence names ids, URLs and counts, never values.`
        : offered.length
          ? 'golive registers checks for this axis, but none of them runs on this stack: confirm it by hand or in the provider dashboard.'
          : 'golive has no registered check for this axis: confirm it by hand or in the provider dashboard.',
    });
  }
  rows.push({
    subject: 'whole app',
    commands: ['golive doctor', 'golive plan', 'golive apply --plan <planId> --yes', 'golive verify'],
    note: 're-observe, re-approve, then apply: a changed destination needs a new plan and fresh confirmation.',
  });
  rows.push({
    subject: 'this document',
    commands: ['golive handoff --write --force'],
    note: 'regenerates GOLIVE_HANDOVER.md and .golive/handover.json from current state and provider reads.',
  });
  return rows;
}

// ── Retirement ──────────────────────────────────────────────────────────────────────────────────

function retirementRows(ctx: Ctx, inventory: Inventory): HandoverRetirement[] {
  const rows: HandoverRetirement[] = [];
  for (const r of inventory.dnsRecords) {
    rows.push({
      resource: `${r.providerTitle} ${r.record.type} ${r.record.name} (golive-created)`,
      how: 'golive teardown → apply --plan <id> --yes --confirm-destroy --confirm-dns, which re-reads the zone to prove the record is gone',
      removable: true,
      provenance: { kind: 'verified' },
    });
  }
  for (const w of inventory.webhooks) {
    rows.push({
      resource: `${w.providerTitle} ${w.mode}-mode webhook endpoint ${w.id}`,
      how: w.removal
        ? `golive teardown → apply --plan <id> --yes --confirm-destroy${w.mode === 'live' ? ' --confirm-live' : ''}`
        : `by hand in the ${w.providerTitle} dashboard: golive cannot remove it right now`,
      removable: Boolean(w.removal),
      provenance: { kind: 'recorded', at: recordedAt(ctx, RECORDING_STEP.webhook) },
    });
  }
  for (const k of inventory.sendingKeys) {
    rows.push({
      resource: `${k.providerTitle} sending key ${k.id} (${k.target})`,
      how: k.revocation
        ? 'golive teardown → apply --plan <id> --yes --confirm-destroy'
        : `by hand in the ${k.providerTitle} dashboard: golive cannot revoke it right now`,
      removable: Boolean(k.revocation),
      provenance: { kind: 'recorded', at: recordedAt(ctx, [`email:key:${k.target}`]) },
    });
  }
  if (inventory.project) {
    rows.push({
      resource: `${inventory.project.providerTitle} project ${inventory.project.name ?? inventory.project.id} (${inventory.project.id})`,
      how: inventory.project.created
        ? 'golive teardown → apply --plan <id> --yes --confirm-destroy'
        : `by hand in the ${inventory.project.providerTitle} dashboard: golive adopted this project and will not delete it`,
      removable: inventory.project.created,
      provenance: { kind: 'recorded', at: recordedAt(ctx, RECORDING_STEP.project) },
    });
  } else {
    // The host was not usable for an inventory this run: report what state links instead of dropping it.
    const host = adapterFor(ctx, 'hosting');
    const linked = host ? ctx.state.resource(projectStateKeys(host.id).id) : undefined;
    if (host && linked) {
      rows.push({
        resource: `${host.title} project ${ctx.state.resource(projectStateKeys(host.id).name) ?? linked} (${linked})`,
        how: `by hand in the ${host.title} dashboard, or run \`golive teardown\` once its login and removal capability are available`,
        removable: false,
        provenance: { kind: 'recorded', at: recordedAt(ctx, RECORDING_STEP.project) },
      });
    }
  }
  for (const r of inventory.recorded.filter((x) => x.created)) {
    rows.push({
      resource: `${r.providerTitle} ${r.kind === 'database-project' ? `project ${r.id}` : `sending domain ${r.name}`}`,
      how: `by hand in ${r.where}: this provider exposes no delete capability to golive`,
      removable: false,
      provenance: { kind: 'recorded', at: recordedAt(ctx, r.kind === 'database-project' ? RECORDING_STEP.database : RECORDING_STEP.domain) },
    });
  }
  return rows;
}

// ── Provenance ──────────────────────────────────────────────────────────────────────────────────

function provenanceRows(at: string, resources: HandoverResource[]): HandoverSectionProvenance[] {
  return [
    { section: 'Accounts and login route', source: 'live `auth()` reads made for this document', at, tags: ['verified', 'unverifiable', 'unknown'] },
    { section: 'Resources created', source: resourcesSource(resources), at, tags: ['verified', 'recorded'] },
    { section: 'Costs and recurrence', source: 'golive.yaml only: no billing, quota or usage read', at, tags: ['unknown'] },
    { section: 'What is manual', source: 'the current plan\'s handoffs and their check results', at, tags: ['verified', 'unverifiable'] },
    { section: 'If it breaks', source: 'the registered checks of this release', at, tags: [] },
    { section: 'Retirement', source: 'the read-only inventory of what golive provably created', at, tags: ['verified', 'recorded', 'unverifiable'] },
  ];
}

/**
 * What the "Resources created" rows were built from: only the reads this run really made, named by
 * the rows they produced. A stack with no DNS record claims no DNS read.
 */
function resourcesSource(resources: HandoverResource[]): string {
  const reads: string[] = [];
  if (resources.some((r) => r.axis === 'dns' && r.provenance.kind === 'verified')) reads.push('the DNS provider\'s owned-record read (this run)');
  if (resources.some((r) => r.kind === 'host project' && r.provenance.kind === 'verified')) reads.push('this run\'s read of the host project');
  return [...reads, 'recorded state'].join(' plus ');
}

// ── Shared ─────────────────────────────────────────────────────────────────────────────────────

/** The axes this app actually uses: a provider id from `golive.yaml` that is not empty. */
function axesUsed(ctx: Ctx): Array<{ axis: Axis; provider: string; providerTitle: string }> {
  const out: Array<{ axis: Axis; provider: string; providerTitle: string }> = [];
  for (const axis of AXES) {
    const provider = ctx.config.stack[axis];
    if (!provider) continue;
    const adapter = adapterById(provider, ctx.adapters);
    out.push({ axis, provider, providerTitle: adapter?.title ?? GUIDED.find((g) => g.id === provider)?.title ?? provider });
  }
  return out;
}
